### ISSUE TITLE
A request for more features

### ISSUE THREAD

**Issue by alekksander** [Kissaki/youtube-speed-controls#3]
Hello. Thank You for developing this one, it really works great and so far it's suiting me best. Since there is active development going on i decided to open a request for:

→better global speed handling  –  to have (for instance) a switch or something to remember next videos on current speed or apply for current only
→configurable values and number of values in preset board  –  to display less or more pre-configured ones and to customize their values
→click on timer icon to reset speed to 1.0
→add ability to show/hide indicator elements  –  yes, even more than now
→work for all yt videos  –  sometimes indicator is not available on youtube video. i will report exact examples in the future, unless it's a known issue?

**Comment by Kissaki** [comment]
Glad it’s useful to you and you enjoy it.

I like the idea of click icon to reset to 1.0.

> →add ability to show/hide indicator elements – yes, even more than now

Can you be more specific about this?

> →work for all yt videos – sometimes indicator is not available on youtube video. i will report exact examples in the future, unless it's a known issue?

There has been an issue before the recent developments and updates a few weeks/17 days ago. If there are still open issues, please report them as an issue ticket.

**Comment by Kissaki** [comment]
I released v1.3.0 with reset on icon click.
